# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Statistical 
author: Spencer A. Hill
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  stderr_output: severe

# Only build files listed in the TOC (i.e. exclude unfinished/"draft" files)
only_build_toc_files: true

# MyST extensions.
parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - colon_fence
    - linkify
    - substitution
  myst_url_schemes: [mailto, http, https]
  myst_dmath_double_inline: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: stat-methods-earth-atmos-sci.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/spencerahill/stat-methods-course
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# C.f. https://jupyterbook.org/en/stable/content/math.html#math-and-equations
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
