name: stats-book-ci
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyter-book
  - ipykernel
  - pytorch >= 2.3  # earlier pytorch versions don't support numpy >=2.0 
  - scikit-learn
  - matplotlib 
  - netcdf4
  - nc-time-axis
  - numpy
  - scipy
  - xarray
  - hvplot
  - pip:
    - git+https://github.com/spencerahill/puffins.git


