name: stats-book-ci
channels:
  - conda-forge
dependencies:
  - python
  - jupyter-book
  - ipykernel
  - jupyter_bokeh
  - matplotlib 
  - hvplot
  - numpy
  - scipy
  - seaborn
  - xarray
  - netcdf4
  - nc-time-axis
  - pytorch
  - scikit-learn

